# Generated by Django 2.2.4 on 2019-09-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produit/images/')),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_produit', models.CharField(max_length=250)),
                ('nom_produit', models.CharField(max_length=250, null=True)),
                ('categorie_produit', models.CharField(max_length=250, null=True)),
                ('niveau', models.CharField(max_length=250, null=True)),
                ('date_ajout_produit', models.DateTimeField(auto_now_add=True)),
                ('date_update_produit', models.DateTimeField(auto_now=True)),
                ('nom_produit_ar', models.CharField(max_length=250, null=True)),
                ('description_produit', models.TextField(null=True)),
                ('description_produit_ar', models.TextField(null=True)),
                ('prix_produit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notice', models.FileField(blank=True, null=True, upload_to='produit/notice/')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.ForeignKey(on_delete='cascade', to='produit.Produit')),
            ],
        ),
    ]
