# Generated by Django 2.2.4 on 2019-09-22 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsfavorite',
            name='id_user',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageproduit',
            name='produit',
            field=models.ForeignKey(on_delete='cascade', to='produit.Produit'),
        ),
        migrations.AlterUniqueTogether(
            name='produitsfavorite',
            unique_together={('id_user', 'id_produit')},
        ),
    ]
