# Generated by Django 2.2.4 on 2019-09-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
