# Generated by Django 2.2.4 on 2019-09-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_blog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Admin/imageVente/')),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
