# Generated by Django 2.2.4 on 2019-09-22 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panier', '0002_panier_user_id_panier_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panier_user',
            name='id_panier_user',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='panier_user',
            unique_together={('id_panier_user', 'id_panier_produit')},
        ),
    ]
