# Generated by Django 2.2.4 on 2019-10-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
