# Generated by Django 2.2.4 on 2019-09-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_commande', models.BooleanField(default=False)),
                ('etat_archive', models.BooleanField(default=False)),
                ('annulation_levraison', models.BooleanField(default=False)),
                ('note_dannulation', models.CharField(blank=True, default=' ', max_length=250)),
                ('bon_de_commande', models.CharField(blank=True, max_length=250)),
                ('bon_de_livraison', models.ImageField(blank=True, upload_to='commande/images/')),
                ('date_commande', models.DateTimeField(blank=True)),
                ('date_levraison', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('id_commande', models.ForeignKey(on_delete='cascade', to='commande.Commande')),
            ],
        ),
    ]
