# Generated by Django 2.2.4 on 2019-09-22 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0002_ligne_commande_id_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='id_point_vente',
            field=models.ForeignKey(on_delete='cascade', related_name='point_vente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_user',
            field=models.ForeignKey(on_delete='cascade', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ligne_commande',
            unique_together={('id_commande', 'id_produit')},
        ),
    ]
